export const strings = {
  // ** Common Strings
  cancel: 'Cancel',
  partners: 'Partners',
  drivers: 'Drivers',
  driver: 'Driver',
  users: 'Users',
  name: 'Name',
  country: 'Country',
  title: 'Title',
  field: 'Field',
  status: 'Status',
  search: 'Search',
  actions: 'Actions',
  run: 'Run',
  view: 'View',
  edit: 'Edit',
  delete: 'Delete',
  statusLabel: 'Status',
  suspend: 'Suspend',
  updateStatus: 'Update Status',
  save: 'Save',
  createdAt: 'Created at',
  wallet: 'Wallet',
  trips: 'Trips',
  walletHistory: 'Wallet History',
  ratings: 'Ratings',
  rating: 'Rating',
  comment: 'Comment',
  paymentMethod: 'Payment Method',
  cost: 'Cost',
  star: 'STAR',
  startDate: 'Start Date',
  endDate: 'End Date',
  uploadImage: 'Upload Image',
  updatePassword: 'Update Password',
  upload: 'Upload',
  uploadFile: 'Upload File',
  uploadExcel: 'Upload Excel',
  downloadSampleExcel: 'Download Sample Excel File',
  selectExcel: 'Select Excel File',
  download: 'Download',
  uploadViaExcel: 'Upload Via Excel',
  preview: 'Preview',
  excel: 'Excel',
  reset: 'Reset',
  allowedImageExtension: 'Allowed PNG, JPG and JPEG. Max size of 1.2 Mb.',
  maxImageSize: 'File size too large, max file size is 1.2 Mb.',
  alphabetsAllowed: 'Only alphabets allowed',
  alphabetsUnderscoreAllowed: 'Only lowercase letters and underscores are allowed, whitespace not allowed',
  noDataFound: 'No Data Found',
  car: 'Car',

  // ** Login
  signInText: 'Please sign-in to your account and start the adventure',
  email: 'Email',
  password: 'Password',
  rememberMe: 'Remember Me',
  forgotPassword: 'Forgot Password?',
  login: 'Login',
  altLogoImage: 'Optilab-logo',
  passwordPatternMsg:
    'Password must contain 8 characters, 1 uppercase, 1 lowercase, 1 number and 1 special case character, whitespace not allowed',
  loginImageAltText: 'login-illustration',
  registerImageAltText: 'register-illustration',

  // *** Validation Messages
  loginEmailRequiredErrorMsg: 'Please enter email',
  loginEmailValidationErrorMsg: 'Please enter a valid email',
  loginPasswordRequiredErrorMsg: 'Please enter password',
  confirmPasswordRequiredErrorMsg: 'Please enter confirm password',
  confirmPasswordMatchErrorMsg: 'The password do not match',

  // ** Forgot Password
  forgotPasswordTitle: 'Forgot Password? 🔒',
  forgotPasswordText: `Enter your email and we'll send you instructions to reset your password`,
  resetCodeText: 'Send reset code',
  backToLogin: 'Back to login',
  forgotPasswordImageAltText: 'forgot-password-illustration',

  // ** Reset Password
  resetPasswordTitle: 'Reset Password 🔒',
  resetPasswordText: 'Your new password must be different from previously used passwords',
  newPassword: 'New Password',
  confirmPassword: 'Confirm Password',
  setNewPassword: 'Set New Password',
  resetPasswordImageAltTest: 'reset-password-illustration',

  // ** Verify Email
  verifyEmail: 'Verify your email ✉️',
  verifyEmailImageAltText: 'verify-email-illustration',
  verifyEmailText:
    'We sent a verification code to your register email. Enter the code from the mail in the field below.',
  skipForNow: 'Skip for now',
  getMail: `Didn't get the mail?`,
  resend: 'Resend',
  resendMsg: 'Resend code successfully',
  otpNotMatched: 'Otp does not matched',
  invalidEmail: 'Invalid Email',

  // ** Admins
  addAdmin: 'Add Admin',
  addNewAdmin: 'Add New Admin',
  registerNameReqMsg: 'Please enter name',
  registerNamePlaceholder: 'Name',
  registerNameMinLengthMsg: 'Please enter more than 2 character',
  alphabetsAllowed: 'Please enter only alphabets',
  countryReqMsg: 'Please select country',
  roleReqMsg: 'Please select role',
  adminTitle: 'Admin List',
  adminsTitleHeaderNameLabel: 'admin',
  adminsTitleHeaderNameField: 'full_name',
  adminsTitleHeaderEmailLabel: 'email',
  adminsTitleHeaderCountryLabel: 'country',
  adminsTitleHeaderRoleLabel: 'role',
  adminsTitleHeaderStatusLabel: 'status',
  adminsTitleHeaderActionLabel: 'action',
  View: 'View',
  Edit: 'Edit',
  Delete: 'Delete',
  editAdmin: 'Edit Admin',
  viewAdmin: 'View Admin',
  adminNameLabel: 'Name',
  adminNamePlaceHolder: 'John',
  adminMiddleNamePlaceHolder: 'J',
  adminLastNamePlaceHolder: 'Doe',
  adminEmailLabel: 'Email',
  adminEmailPlaceHolder: 'johndoe@email.com',
  adminResetpassword: 'Reset password',
  adminCountryLabel: 'Country',
  adminCountryPlaceHolder: 'India',
  adminRoleLabel: 'Role',
  adminRolePlaceHolder: 'Admin',
  backButton: 'Back',
  cancelButton: 'Cancel',
  submitButton: 'Submit',
  failToGetAdminsList: 'Fail to get admin list',
  addAdminsMsg: 'New admin created successfully !!!',
  failToAddAdminsMsg: 'Fail to add admin data',
  failToGetAdminsDetailMsg: 'Fail to get admin details',
  updateAdminsMsg: 'Admin data update successfully',
  failToUpdateAdminsMsg: 'Admin is not updated',
  updateAdminsStatusMsg: 'Admin status updates successfully',
  failToUpdateAdminsStatusMsg: 'Fail to update admin status',
  deleteAdminsMsg: 'Admin deleted successfully',
  failToDeleteAdminsMsg: 'Fail to delete admin',
  updateAdminsPasswordMsg: 'Password updated successfully',
  failedToUpdateAdminsPasswordMsg: 'Fail to update password',

  invalidEmail: '⚠️ Invalid Email',

  //** Partners */
  addPartners: 'Add Partner',
  partnersTitle: 'Partner',
  partnersFieldTitle: 'partner_title',
  partnersEmailTitle: 'Email',
  partnersEmailFieldTitle: 'email',
  partnersTitleHeaderCountryLabel: 'country',
  partnersTitleHeaderCityLabel: 'city',
  partnersTitleHeaderStatusLabel: 'status',
  partnersTitleHeaderActionLabel: 'action',
  partnersDrivers: 'Drivers',
  partnersCars: 'Cars',

  // ** Partners Response/Toast Messages
  failToGetPartnersList: 'Fail to get partner list',
  addPartnersMsg: 'Add partner successfully',
  failToAddPartnersMsg: 'Fail to add partner data',
  failToGetPartnersDetailMsg: 'Fail to get partner details',
  updatePartnersMsg: 'Partner data update successfully',
  failToUpdatePartnersMsg: 'Fail to update partner data',
  updatePartnersStatusMsg: 'Partner status updates successfully',
  failToUpdatePartnersStatusMsg: 'Fail to update partner status',
  deletePartnersMsg: 'Partner deleted successfully',
  failToDeletePartnersMsg: 'Fail to delete partner',
  failToGetDriverList: 'Fail to get drivers list',
  failToGetCarsList: 'Fail to get cars list',

  // ** Profile
  profileDetailsLabel: 'Details',
  profileTotalTripLabel: 'Total Trip',
  profileRatingsLabel: 'Ratings',
  profileEmailLabel: 'Email',
  profileMobileNoLabel: 'Mobile No.',
  profileRoleLabel: 'Role',
  profileContactLabel: 'Contact',
  profileCompanyEmailLabel: 'Company Email',
  profileCompanyAddressLabel: 'Company Address',
  profileTaxIdLabel: 'U ID',
  profileLanguageLabel: 'Language',
  profileCountryLabel: 'Country',
  profileEditButtonLabel: 'Edit',
  profileSuspendButtonLabel: 'Suspend',
  profileActiveStatusLabel: 'Active Status',
  profileOverviewLabel: 'Overview',
  profileSecurityLabel: 'Security',
  editDetails: 'Edit Details',

  // ** Profile Change Password
  profileUpdatePasswordLabel: 'Change Password',
  profileUpdatePasswordNote: 'Ensure that these requirements are met',
  profileUpdatePasswordMessage: 'Minimum 8 characters long, uppercase & symbol',
  profileNewPasswordLabel: 'New Password',
  profileConfirmNewPasswordLabel: 'Confirm New Password',
  profileChangePasswordButton: 'Change Password',

  // ** Profile Login Histories
  ProfileLoginHistoriesLabel: 'Login Histories',
  IPAddressHeaderLabel: 'IP Address',
  DeviceHeaderLabel: 'Device',
  LocationHeaderLabel: 'Location',
  RecentActivityHeaderLabel: 'Recent Activity',

  // ** Profile Recent devices
  profileRecentDevicesLabel: 'Recent devices',
  profileDeviceHeaderLabel: 'Device',
  profileLocationHeaderLabel: 'Location',
  profileRecentActivityHeaderLabel: 'Recent Activity',

  // ** Profile toast message
  failToViewProfileDataMsg: 'Failed to fetch profile details',
  passwordUpdateSuccessfulMsg: 'Password updated successfully',
  failToUpdateProfilePassword: 'Failed to update password',

  // ** Permissions
  failPermissionList: 'Failed to fetch permission list',
  failToGetPermissionsList: 'Unable to get permissions list',
  permissionModuleDataField: 'moduleData',
  permissionModuleNameHeaderName: 'Module Name',
  permissionAssignedToField: 'assignedTo',
  permissionAssignedToHeaderName: 'Assigned To',

  // ** Roles
  failRoleList: 'Failed to fetch role list',
  successAddRoleMsg: 'Role added successfully',
  failAddRoleMsg: 'Failed to add role',
  successUpdateRoleMsg: 'Role updated successfully',
  failUpdateRoleMsg: 'Failed to update role',
  failViewRoleMsg: 'Failed to fetch role details',
  failViewEmployeeByRoleMsg: 'Failed to fetch role details',
  successDeleteRoleMsg: 'Role deleted successfully',
  failDeleteRoleMsg: 'Failed to delete role',

  // ** Documents
  addFieldBtnText: 'Add Field',
  no: 'No',
  found: 'Found',
  addNewFieldFor: 'Add new field for',
  editNewFieldFor: 'Edit new field for',
  documentTitlePlaceholder: 'E.g. First Name',
  documentFieldName: 'Field Name',
  documentFieldPlaceholder: 'E.g. first_name',
  documentValidationTitle: 'Validation',
  documentRequiredTitle: 'Required',
  documentOptionalTitle: 'Optional',
  documentTypeTitle: 'Type',

  // *** Documents Validation Messages
  documentTitleReqMsg: 'Please enter title',
  documentFieldReqMsg: 'Please enter field',
  documentValidationReqMsg: 'Please select validation',
  documentTypeReqMsg: 'Please select type',
  documentCountryReqMsg: 'Please select country',

  // ** Documents Toast Messages
  failDocumentList: 'Failed to fetch document list',
  successAddDocumentMsg: 'Document added successfully',
  failAddDocumentMsg: 'Failed to add document',
  failViewDocumentMsg: 'Failed to fetch document details',
  successUpdateDocumentMsg: 'Document updated successfully',
  failUpdateDocumentMsg: 'Failed to update document',
  successStatusUpdateDocumentMsg: 'Document status updated successfully',
  failStatusUpdateDocumentMsg: 'Failed to update document status',
  successDeleteDocumentMsg: 'Document deleted successfully',
  failDeleteDocumentMsg: 'Failed to delete document',

  // ** Custom Components
  deleteDialogDefaultHeading: `Are you sure ?`,
  deleteDialogForceDeleteText: `Do you still want to delete?`,
  deleteDialogForceDeleteButtonText: `Force Delete`,
  deleteDialogDefaultDescription: `You won't be able to revert this!`,
  deleteDialogCancelButtonText: `Cancel`,
  deleteDialogDeleteButtonText: `Delete`,
  deleteDialogOkButtonText: `Ok`,
  resetPasswordDialogDefaultHeading: `Reset Password`,
  resetPasswordDialogConfirmText: `Reset Password`,
  resetPasswordDialogCancelButtonText: `Cancel`,
  resetPasswordFieldKeyPassword: 'password',
  resetPasswordFieldLabelPassword: 'New Password',
  resetPasswordFieldKeyConfirmPassword: 'confirm_password',
  resetPasswordFieldLabelConfirmPassword: 'Confirm New Password',
  sendNotificationDialogDefaultHeading: 'Send Notification',
  sendNotificationDialogConfirmText: 'Send',
  sendNotificationDialogKeyTitle: 'title',
  sendNotificationDialogKeyTitleLabel: 'Title',
  sendNotificationDialogKeyTitleReqMsg: 'Please enter title',
  sendNotificationDialogKeyDescriptionReqMsg: 'Please enter description',
  sendNotificationDialogKeyDescription: 'description',
  sendNotificationDialogKeyDescriptionLabel: 'Description',
  sendNotificationDialogKeyChannels: 'channels',
  sendNotificationDialogKeyChannelsLabel: 'Channels',
  sendNotificationDialogKeyChannelsReqMsg: 'Please select at least one channel',
  sendNotificationDialogAppNotificationLabel: 'App Notification',
  sendNotificationDialogSMSLabel: 'SMS',
  sendNotificationDialogEmailLabel: 'Email',
  changeStatusDialogDefaultHeading: 'Change Status',
  changeStatusDialogFieldLabel: 'Status',
  changeStatusDialogConfirmText: 'Update',

  // basic
  companyNameKey: 'company_name',
  companyNameLabel: 'Company Name',
  companyNamePlaceholder: 'E.g. ATMM Technology DOO ',
  companyNameRequiredMsg: 'Please enter a company name',
  companyNameMinLengthMsg: 'Please enter a company name with more than 2 character',
  mobileKey: 'mobile_no',
  mobileLabel: 'Mobile No.',
  mobilePlaceholder: 'E.g. 9999999999',
  mobileRequiredMsg: 'Please enter a mobile no.',
  mobileMinLengthMsg: 'Please enter a mobile no. with 10 digits',
  alternateMobileKey: 'alternate_mobile',
  alternateMobileLabel: 'Alternate Mobile No.',
  alternateMobilePlaceholder: 'E.g. 9999999999',
  alternateMobileMinLengthMsg: 'Please enter a mobile no. with 10 digits',
  basicEmailKey: 'email',
  emailLabel: 'Email',
  emailPlaceholder: 'E.g. rahul@gmail.com',
  emailRequiredMsg: 'Please enter an email',
  emailPatternMsg: 'Please enter a valid email',
  AddressOneLabel: 'Address Line 1',
  AddressOneKey: 'address_one',
  AddressOneReqMsg: 'Please enter an address line 1',
  AddressOnePlaceholder: 'E.g. 105-B, Anjani Aangan Society, Anand',
  AddressTwoLabel: 'Address Line 2',
  AddressTwoKey: 'address_two',
  AddressTwoReqMsg: 'Please enter an address line 1',
  AddressTwoPlaceholder: 'E.g. 105-B, Anjani Aangan Society, Anand',
  vatKey: 'vat_no',
  vatLabel: 'VAT',
  vatPlaceholder: 'E.g. 999999999',
  vatRequiredMsg: 'Please enter a vat',
  vatMinLengthMsg: 'Please enter a vat with 9 digits',
  registerKey: 'register_no',
  registerLabel: 'Register Number',
  registerPlaceholder: 'E.g. 999999999',
  registerRequiredMsg: 'Please enter a register number',
  registerMinLengthMsg: 'Please enter a register number with 12 digits',
  numberAllowedOnly: 'Only numbers are allowed',
  websiteKey: 'website',
  websiteLabel: 'Website',
  websitePlaceholder: 'E.g. https://optilab.eu ',
  websiteRequiredMsg: 'Please enter a website url',
  websiteValidUrlMsg: 'Please enter a valid url',
  bankAccountField: 'Bank Account Setting',
  ibanKey: 'iban_code',
  ibanRequiredMsg: 'Please enter IBAN code',
  ibanLabel: 'IBAN Code',
  ibanPlaceholder: 'E.g. AL47 2121 1009 0000 0002 3569 87411',
  ibanValidUrlMsg: 'Please enter a valid IBAN code',
  accountHolderNameKey: 'name_in_bank',
  accountHolderNameRequiredMsg: 'Please enter account holder name',
  accountHolderNameLabel: 'Account Holder Name',
  accountHolderNamePlaceholder: 'E.g. John Doe',
  accountHolderNameValidUrlMsg: 'Please enter a valid name',
  bankNameKey: 'bank_name',
  bankNameRequiredMsg: 'Please enter a bank',
  bankNameLabel: 'Bank Name',
  bankNamePlaceholder: 'E.g. BOB',
  ibcKey: 'ibc_code',
  ibcRequiredMsg: 'Please enter IBC code',
  ibcLabel: 'IBC Code',
  ibcPlaceholder: 'E.g. HBUK GB 4B XXX',
  ibcValidUrlMsg: 'Please enter a valid IBC code',
  ibcMinLengthMsg: 'Please enter a IBC code with minimum 8 digits',
  ibcMaxLengthMsg: 'Please enter a IBC code with maximum 11 digits',
  currencyKey: 'currency',
  currencyLabel: 'Currency',
  currencyPlaceHolder: 'Euro',
  statusKey: 'status',
  statusLabel: 'Status',
  timezoneLabel: 'Time Zone',
  statusPlaceHolder: '(GMT-11:00) International Date Line West',
  saveChangesButton: 'Save Changes',

  // ** Car Category
  carCategoryPricingMenuItem: 'Pricing',
  carCategoryDrawerTitle: 'Add New Category',
  carCategoryAddFieldBtnText: 'Add Category',

  // ** Car Brand Response/Toast Messages
  failToGetCarBrandList: 'Unable to get car brand list',
  addCarBrandMsg: 'Car brand added successfully',
  failToAddCarBrandMsg: 'Failed to add car brand',
  failToGetCarBrandDetailMsg: 'Unable to get car brand detail',
  updateCarBrandMsg: 'Car brand updated successfully',
  failToUpdateCarBrandMsg: 'Unable to update car brand',
  updateCarBrandStatusMsg: 'Status updated successfully',
  failToUpdateCarBrandStatusMsg: 'Failed to update status',
  deleteCarBrandMsg: 'Car brand deleted successfully',
  failToDeleteCarBrandMsg: 'Failed to delete car brand',
  uploadExcelCarBrandMsg: 'Excel uploaded successfully',
  failToUploadExcelCarBrandMsg: 'Failed to upload excel',

  // ** Car Brand Response/Toast Messages
  failToGetCarCategoryList: 'Unable to get car category list',
  addCarCategoryMsg: 'Car category added successfully',
  failToAddCarCategoryMsg: 'Failed to add car category',
  failToGetCarCategoryDetailMsg: 'Unable to get car category detail',
  updateCarCategoryMsg: 'Car category updated successfully',
  failToUpdateCarCategoryMsg: 'Unable to update car category',
  updateCarCategoryStatusMsg: 'Status updated successfully',
  failToUpdateCarCategoryStatusMsg: 'Failed to update status',
  deleteCarCategoryMsg: 'Car category deleted successfully',
  failToDeleteCarCategoryMsg: 'Failed to delete car category',

  // ** Car Category City pricing/Toast Messages
  failToGetCityPricingList: 'Unable to get city pricing list',
  addCityPricingMsg: 'City pricing added successfully',
  failToAddCityPricingMsg: 'Failed to add city pricing',
  failToGetCityPricingDetailMsg: 'Unable to get city pricing detail',
  updateCityPricingMsg: 'City pricing updated successfully',
  failToUpdateCityPricingMsg: 'Unable to update city pricing',
  updateCityPricingStatusMsg: 'Status updated successfully',
  failToUpdateCityPricingStatusMsg: 'Failed to update status',
  deleteCityPricingMsg: 'City pricing deleted successfully',
  failToDeleteCityPricingMsg: 'Failed to delete city pricing',

  // ** Car brand list
  carBrandsTitle: 'Car Brands',
  carBrandName: 'Name',
  actionsLabel: 'Action',
  searchCarBrandPlaceholder: 'Search',
  addBrandButton: 'Add Brand',
  editCarBrandLabel: 'Edit',
  deleteCarBrandLabel: 'Delete',
  deleteCarBrandTitle: 'Delete Brand',

  // ** Add / edit car brand
  newCarBrandLabel: 'New Brand',
  carBrandNameKey: 'title',
  carBrandNameLabel: 'Name',
  carBrandNamePlaceholder: 'Name',
  carBrandNameReqMsg: 'Car brand name is required',
  carBrandStatusKey: 'activity_status',
  carBrandStatusLabel: 'status',
  carBrandSubmitButton: 'Save',
  carBrandCancelButton: 'Cancel',

  // ** Car Model Response/Toast Messages
  failToGetCarModelList: 'Unable to get car model list',
  addCarModelMsg: 'Car model added successfully',
  failToAddCarModelMsg: 'Failed to add car model',
  failToGetCarModelDetailMsg: 'Unable to get car model detail',
  updateCarModelMsg: 'Car model updated successfully',
  failToUpdateCarModelMsg: 'Unable to update car model',
  updateCarModelStatusMsg: 'Status updated successfully',
  failToUpdateCarModelStatusMsg: 'Failed to update status',
  deleteCarModelMsg: 'Car model deleted successfully',
  failToDeleteCarModelMsg: 'Failed to delete car model',
  uploadExcelFileCarModelMsg: 'Excel uploaded successfully',
  failToUploadExcelFileCarModelMsg: 'Failed to upload excel',

  // ** Car model list
  carModelsTitle: 'Car Models',
  carModelName: 'Name',
  carModelBrandName: 'Brand',
  actionsLabel: 'Action',
  searchCarModelPlaceholder: 'Search',
  addModelButton: 'Add Model',
  editCarModelLabel: 'Edit',
  deleteCarModelLabel: 'Delete',
  deleteCarModelTitle: 'Delete Model',

  // ** Add / edit car model
  newCarModelLabel: 'New Model',
  carModelNameKey: 'name',
  carModelNameLabel: 'Name',
  carModelNamePlaceholder: 'Name',
  carModelNameReqMsg: 'Car model name is required',
  carModelBrandNameKey: 'car_brands_u_id',
  carModelBrandNameLabel: 'Brand',
  carModelBrandNameReqMsg: 'Select car brand name',
  carBrandNotFoundLabel: 'Data not found',
  carModelStatusKey: 'activity_status',
  carModelStatusLabel: 'status',
  carModelSubmitButton: 'Save',
  carModelCancelButton: 'Cancel',

  // ** city Response/Toast Messages
  failToGetCityList: 'Unable to get city list',
  addCityMsg: 'City added successfully',
  failToAddCityMsg: 'Failed to add city',
  failToGetCityDetailMsg: 'Unable to get city detail',
  updateCityMsg: 'City updated successfully',
  failToUpdateCityMsg: 'Unable to update city',
  updateCityStatusMsg: 'Status updated successfully',
  failToUpdateCityStatusMsg: 'Failed to update status',
  deleteCityMsg: 'City deleted successfully',
  failToDeleteCityMsg: 'Failed to delete city',

  // ** city list
  countryLabel: 'Country',
  cityLabel: 'City',
  latitudeLabel: 'Latitude',
  longitudeLabel: 'Longitude',
  actionsLabel: 'Action',
  searchCityPlaceholder: 'Search',
  addCityButton: 'Add City',
  editCityLabel: 'Edit',
  deleteCityLabel: 'Remove',
  deleteCityTitle: 'Remove City',

  // ** Add / edit city
  newCityLabel: 'New City',
  cityNameKey: 'name',
  cityNameLabel: 'City',
  cityNamePlaceholder: 'City',
  cityNameReqMsg: 'City is required',
  cityLatitudeKey: 'lat',
  cityLatitudeLabel: 'Latitude',
  cityLatitudePlaceholder: 'Latitude',
  cityLatitudeReqMsg: 'Latitude is required',
  cityLongitudeKey: 'lng',
  cityLongitudeLabel: 'Longitude',
  cityLongitudePlaceholder: 'Longitude',
  cityLongitudeReqMsg: 'Longitude is required',
  cityCountryNameKey: 'country_u_id',
  cityCountryNameLabel: 'Country',
  cityCountryNameReqMsg: 'Please select country',
  cityStatusKey: 'activity_status',
  cityStatusLabel: 'status',
  citySubmitButton: 'Save',
  cityCancelButton: 'Cancel',

  // ** Basic details
  updateBasicMsg: 'Setting updated successfully',
  failToUpdateBasicMsg: 'Failed to Setting update setting',
  failToGetBasicDetailMsg: 'Failed to get basic details',

  // ** Campaigns Toast Messages
  failCampaignList: 'Failed to fetch campaign list',
  successAddCampaignMsg: 'Campaign added successfully',
  failAddCampaignMsg: 'Failed to add campaign',
  successRunCampaignMsg: 'Campaign run successfully',
  failRunCampaignMsg: 'Failed to run campaign',
  failViewCampaignMsg: 'Failed to fetch campaign details',
  successUpdateCampaignMsg: 'Campaign updated successfully',
  failUpdateCampaignMsg: 'Failed to update campaign',
  successStatusUpdateCampaignMsg: 'Campaign status updated successfully',
  failStatusUpdateCampaignMsg: 'Failed to update campaign status',
  successDeleteCampaignMsg: 'Campaign deleted successfully',
  failDeleteCampaignMsg: 'Failed to delete campaign',

  // ** Campaigns
  addCampaignBtnText: 'Add Campaign',
  campaignDeleteTitle: 'Delete Campaign',
  campaignTitle: 'Campaign',
  campaignPlaceholderTitle: 'Eg. New Campaign',
  campaignUsageTitle: 'Usage',
  campaignChannelsTitle: 'Channels',
  campaignViaTitle: 'Via',
  campaignTripsTitle: 'Trips',
  campaignTripsEnabledTitle: 'Trips Enabled',
  campaignComparisonTitle: 'Comparison',
  campaignCountTitle: 'Count',
  campaignUsersTitle: 'Users',
  campaignUserStatusTitle: 'User Status',
  campaignLanguageTitle: 'Language',
  campaignEnableBusinessTitle: 'Enable Business',
  campaignBusinessStatusTitle: 'Business Status',
  campaignTextPushMessageDetailsTitle: 'Text/Push Message Details',
  campaignTextPushTitle: 'Text Title',
  campaignTextPushPlaceholderTitle: 'New Notification!',
  campaignTemplateTitle: 'Template',
  campaignMessageTitle: 'Message',
  campaignMailMessageDetailsTitle: 'Mail Message Details',
  campaignMailSubjectTitle: 'Subject',
  campaignMailSubjectPlaceholderTitle: 'New Mail!',
  noCampaignsFound: 'No Campaigns Found',
  noTripsFound: 'No Trips Found',

  // ** country Response/Toast Messages
  failToGetCountryList: 'Unable to get country list',
  updateOnBoardCountryStatusMsg: 'Country successfully add into on board',
  failToOnBoardUpdateCountryMsg: 'Unable to add country into on board',
  updateCountryStatusMsg: 'Status updated successfully',
  failToUpdateCountryStatusMsg: 'Failed to update status',
  deleteCountryMsg: 'Country successfully remove',
  failToDeleteCountryMsg: 'Failed to remove country',
  updateCountryMsg: 'Country updated successfully',
  failToUpdateCountryMsg: 'Failed to update country',

  // ** On board country list
  onBoardCountriesNameLabel: 'On Board Countries',
  countriesNameLabel: 'Countries',
  countryNameLabel: 'Country',
  cityCountLabel: 'City',
  currencySymbolNameLabel: 'Currency symbol',
  alpha2Label: 'Alpha2',
  alpha3Label: 'Alpha3',
  prefixLabel: 'Prefix',
  countryStatus: 'Status',
  onBoardCountryRemoveLabel: 'Remove From On Board',
  removeCountryLabel: 'Remove',
  removeOnBoardCountryLabel: 'From On Board',
  addOnBoardCountry: 'On Board',
  countryYesButton: `Yes, i'm sure`,

  // ** advance
  partnerInvoicePreKey: 'partner_invoice_prefix',
  partnerInvoicePreLabel: 'Partner Invoice Prefix',
  partnerInvoicePrePlaceholder: 'E.g. PRT- ',
  partnerInvoicePreRequiredMsg: 'Please enter a invoice prefix',
  partnerInvoicePreMinLengthMsg: 'Please enter a  invoice prefix with more than 2 character',
  partnerInvoiceNumKey: 'partner_invoice_number',
  partnerInvoiceNumLabel: 'Partner Invoice Number',
  partnerInvoiceNumPlaceholder: 'E.g. 30',
  partnerInvoiceNumRequiredMsg: 'Please enter a invoice no.',
  partnerInvoiceNumMinLengthMsg: 'Please enter a invoice no. with 1 digits',
  clientInvoicePreKey: 'client_invoice_prefix',
  clientInvoicePrePlaceholder: 'E.g. CLI- ',
  clientInvoiceNumKey: 'client_invoice_no',
  clientInvoiceNumPlaceholder: 'E.g. 30',
  driverRequestTimeoutKey: 'driver_req_timeout',
  driverRequestTimeoutPlaceholder: 'E.g. 30',
  passwordResetTimeoutKey: 'password_reset_timeout',
  passwordResetTimeoutPlaceholder: 'E.g. 30',
  driverSearchRadiusTimeoutKey: 'driver_radius',
  driverSearchRadiusTimeoutPlaceholder: 'E.g. 3000',
  imageMimiTypeKey: 'image_mime_type',
  imageMimiTypeKeyPlaceholder: 'E.g. jpg,png',

  // ** Language
  languagesNamePlaceHolder: 'English',
  languagesNameKey: 'name',

  languagesShortNamePlaceHolder: 'en',
  languagesShortNameKey: 'shortcut',
  languagesRtlKey: 'rtl',
  languagesRtlLabel: 'Right to Left',
  languagesRtlReqMsg: 'Please select rtl',

  failToGetLanguageList: 'Fail to get language list',
  addLanguageMsg: 'New language created successfully !!!',
  failToAddLanguageMsg: 'Fail to add language data',
  failToGetLanguageDetailMsg: 'Fail to get language details',
  updateLanguageMsg: 'Language data update successfully',
  failToUpdateLanguageMsg: 'Language is not updated',
  updateLanguageStatusMsg: 'Language status updates successfully',
  failToUpdateLanguageStatusMsg: 'Fail to update language status',
  deleteLanguageMsg: 'Language deleted successfully',
  failToDeleteLanguageMsg: 'Fail to delete language',
  reasonLanguageKey: 'language',
  reasonForKey: 'reason_for',
  reasonMultiplePlaceholder: 'Reason',

  addCancelReasonMsg: 'New Cancel Reason created successfully !!!',
  updateCancelReasonMsg: 'Cancel Reason data update successfully',
  failToGetCancelReasonList: 'Fail to get cancel reason list',
  failToAddCancelReasonMsg: 'Fail to add cancel reason data',
  failToUpdateCancelReasonMsg: 'Cancel reason is not updated',
  updateCancelReasonStatusMsg: 'Cancel reason status updates successfully',
  failToUpdateCancelReasonStatusMsg: 'Fail to update cancel reason status',
  deleteCancelReasonMsg: 'Cancel reason deleted successfully',
  failToDeleteCancelReasonMsg: 'Fail to delete cancel reason',

  // ** email template Response/Toast Messages
  failToGetEmailTemplateList: 'Unable to get email template list',
  addEmailTemplateMsg: 'Email template added successfully',
  failToAddEmailTemplateMsg: 'Failed to add email template',
  failToGetEmailTemplateDetailMsg: 'Unable to get email template detail',
  updateEmailTemplateMsg: 'Email template updated successfully',
  failToUpdateEmailTemplateMsg: 'Unable to update email template',
  updateEmailTemplateStatusMsg: 'Status updated successfully',
  failToUpdateEmailTemplateStatusMsg: 'Failed to update status',
  deleteEmailTemplateMsg: 'Email template deleted successfully',
  failToDeleteEmailTemplateMsg: 'Failed to delete email template',

  // **  email template list
  emailTemplateEditButton: 'Edit',
  emailTemplateDeleteButton: 'Delete',
  deleteEmailTemplateTitle: 'Delete Email Template',
  emailTemplateTitleHeaderLabel: 'Subject',
  emailTemplateLanguageHeaderLabel: 'Language',
  addEmailTemplateButton: 'Add Email Template',
  emailKey: 'key',
  emailKeyPlaceholder: 'forgot_password',
  emailTemplateKeyHeaderLabel: 'Key',

  // ** add email template
  newEmailTemplateLabel: 'New Email Template',
  emailTemplateTitleKey: 'subject',
  emailTemplateTitleLabel: 'Subject',
  emailTemplateTitlePlaceholder: 'Subject',
  emailTemplateTitleReqMsg: 'Subject is required',
  emailTemplateLanguageNameKey: 'language_u_id',
  emailTemplateLanguageNameLabel: 'Language',
  emailTemplateLanguageNameReqMsg: 'Please select language',
  emailTemplateKey: 'template',
  emailTemplateLabel: 'Template',
  emailTemplatePlaceholder: 'Template',
  emailTemplateReqMsg: 'Template is required',
  emailTemplateStatusKey: 'activity_status',
  emailTemplateSubmitButton: 'Save',
  emailTemplateCancelButton: 'Cancel',

  // ** sms template Response/Toast Messages
  failToGetSmsTemplateList: 'Unable to get sms template list',
  addSmsTemplateMsg: 'Sms template added successfully',
  failToAddSmsTemplateMsg: 'Failed to add sms template',
  failToGetSmsTemplateDetailMsg: 'Unable to get sms template detail',
  updateSmsTemplateMsg: 'Sms template updated successfully',
  failToUpdateSmsTemplateMsg: 'Unable to update sms template',
  updateSmsTemplateStatusMsg: 'Status updated successfully',
  failToUpdateSmsTemplateStatusMsg: 'Failed to update status',
  deleteSmsTemplateMsg: 'Sms template deleted successfully',
  failToDeleteSmsTemplateMsg: 'Failed to delete sms template',

  // **  sms template list
  smsTemplateEditButton: 'Edit',
  smsTemplateDeleteButton: 'Delete',
  deleteSmsTemplateTitle: 'Delete SMS Template',
  smsTemplateTitleHeaderLabel: 'Key',
  smsTemplateLanguageHeaderLabel: 'Language',
  addSmsTemplateButton: 'Add Sms Template',

  // ** add sms template
  newSmsTemplateLabel: 'New Sms Template',
  smsTemplateTitleKey: 'name',
  smsTemplateTitleLabel: 'Title',
  smsTemplateTitlePlaceholder: 'Title',
  smsTemplateTitleReqMsg: 'Title is required',
  smsTemplateLanguageNameKey: 'language_u_id',
  smsTemplateLanguageNameLabel: 'Language',
  smsTemplateLanguageNameReqMsg: 'Please select language',
  smsTemplateKey: 'template',
  smsTemplateLabel: 'Template',
  smsTemplatePlaceholder: 'Template',
  smsTemplateReqMsg: 'Template is required',
  smsTemplateStatusKey: 'activity_status',
  smsTemplateSubmitButton: 'Save',
  smsTemplateCancelButton: 'Cancel',

  // ** static page Response/Toast Messages
  staticPageErrorMsg: 'Unable to get static page list',
  staticPageViewErrorMsg: 'Unable to get static page detail',
  staticPageAddMsg: 'StaticPage add successfully',
  staticPageAddErrorMsg: 'Unable to add static page',
  staticPageDeleteMsg: 'StaticPage delete successfully',
  staticPageDeleteErrorMsg: 'Unable to delete static page',
  staticPageUpdateMsg: 'StaticPage update successfully',
  staticPageUpdateErrorMsg: 'Unable to update static page',
  viewSlugPageErrorMsg: 'Unable to get slug Page detail',
  updateStaticPageStatusMsg: 'Static page status updated successfully',
  failToUpdateStaticPageStatusMsg: 'Unable to update static page status',

  // ** Static-page list
  staticPageHeaderLabel: 'Page',
  staticPageLinkHeaderLabel: 'Link',
  staticPageEditButton: 'Edit',
  staticPageDeleteButton: 'Delete',
  staticPageRemoveTitle: 'Delete Page',
  staticPageDeleteTitle: 'Delete Page',
  staticPageAddButton: 'Add Static Page',

  // ** Static-page add / edit
  staticPageLanguageKey: 'language',
  staticPageLanguageTitleRules: 'Please select language',
  staticPageLanguageTitleLabel: 'Language',
  staticPageLanguageDuplicateMsg: 'This language is already selected',
  staticPageNameKey: 'name',
  staticPageNameTitleRules: 'Name is required',
  staticPageNameTitleLabel: 'Name',
  staticPageNameTitlePlaceHolder: 'Eg:.Term & Conditions',
  staticPageSlugKey: 'slug',
  staticPageSlugTitleRules: 'Slug is required',
  staticPageSlugTitleLabel: 'Slug',
  staticPageSlugTitlePlaceholder: 'term-and-conditions',
  staticPageTemplateKey: 'template',
  staticPageTemplateTitleRules: 'Template is required',
  staticPageTemplateTitleLabel: 'Template',
  staticPageTemplateTitlePlaceholder: 'term-and-conditions',
  staticPageSubmitButton: 'Save',
  staticPageCancelButton: 'Cancel',

  // ** coupon Response/Toast Messages
  failToGetCouponList: 'Unable to get coupon list',
  failToGetCouponUseList: 'Unable to get coupon used by users list',
  addCouponMsg: 'Coupon successfully add',
  failToAddCouponMsg: 'Failed to add coupon',
  updateCouponMsg: 'Coupon updated successfully',
  failToUpdateCouponMsg: 'Unable to update coupon',
  updateCouponStatusMsg: 'Coupon status updated successfully',
  failToUpdateCouponStatusMsg: 'Unable to update coupon status',
  deleteCouponMsg: 'Coupon deleted successfully',
  failToDeleteCouponMsg: 'Failed to delete coupon',
  failToGetCouponDetailMsg: 'Unable to get coupon detail',
  updateCouponVisibleStatusMsg: 'Coupon status updated successfully',
  failToUpdateCouponVisibleStatusMsg: 'Unable to update coupon status',

  // ** roles
  roleNamePlaceholder: 'E.g. Enter a role',
  roleNameRequired: 'Please add a role name',
  roleName: 'name',
  roleLabel: 'Role',
  roleShortCodePlaceholder: 'E.g. Enter a role short code',
  roleShortCodeRequired: 'Please add a role short code',
  roleShortCode: 'short_code',
  roleShortCodeLabel: 'Role Short Code',
  rolesPermissions: 'Module Permissions',
  setRolesPermissions: 'Set Role Permissions',
  roleSelectPermissionMsg: 'Select at least one permission',
  addRoleSubTitle: `Add role, if it doesn't already exist.`,
  roleListTitle: 'Roles List',
  roleListDescription:
    'A role provided access to predefined menus and features so that depending on assigned role an administrator can have access to what he need',
  failToGetRolesList: 'Fail to get Admin List',
  roleKey: 'rol_u_id',
  editRole: 'Edit Role',
  superAdmin: 'admin',
  ownerAdmin: 'owner admin',
  total: 'Total',
  user: 'user',
  users: 'users',
  administratorAccess: 'Administrator Access',
  rolesDetailsTitle: 'Total users of',
  rolesText: 'role',
  roleFieldFirstName: 'first_name',
  roleHeaderFirstName: 'First Name',
  roleFieldLastName: 'last_name',
  roleHeaderLastName: 'Last Name',
  roleFieldEmail: 'email',
  roleHeaderEmail: 'Email',
  roleFieldAddress: 'permanent_address',
  roleHeaderAddress: 'Address',
  roleFieldPhone: 'phone',
  roleHeaderPhone: 'Phone',
  deleteOkButtonText: 'Ok',
  deleteOkButtonColor: '#fdb528',
  rolesPermissionsTitle: 'Roles & Permissions',
  roles: 'Roles',
  addRoleLabel: 'Add Role',
  discardButton: 'Discard',
  selectAll: 'Select All',
  read: 'Read',
  write: 'Write',
  update: 'Update',

  addRoleMsg: 'New role created successfully !!!',
  updateRoleMsg: 'Role data update successfully',
  failToGetRoleList: 'Fail to get role list',
  failToAddRoleMsg: 'Fail to add role data',
  failToUpdateRoleMsg: 'Role is not updated',
  updateRoleStatusMsg: 'Role status updates successfully',
  failToUpdateRoleStatusMsg: 'Fail to update role status',
  deleteRoleMsg: 'Role deleted successfully',
  failToDeleteRoleMsg: 'Fail to delete role',

  emailIdFieldText: 'email',
  fullNameFieldText: 'full_name',
  phoneNoFieldText: 'phone_no',

  // ** Users Toast Messages
  failUserList: 'Failed to fetch users list',
  failViewUserMsg: 'Failed to fetch user details',
  successSuspendUserMsg: 'User suspended successfully',
  failSuspendUserMsg: 'Failed to suspend user',
  successUpdateUserMsg: 'User details updated successfully',
  failUpdateUserMsg: 'Failed to update user details',
  successUpdateUserBusinessDetailsMsg: 'User business details updated successfully',
  failUpdateUserBusinessDetailsMsg: 'Failed to update user business details',
  successStatusUpdateUserMsg: 'User status updated successfully',
  failStatusUpdateUserMsg: 'Failed to update user status',
  successUpdatePasswordUserMsg: 'User password updated successfully',
  failUpdatePasswordUserMsg: 'Failed to update user password',
  successSendNotificationMsg: 'Notification send successfully',
  failSendNotificationMsg: 'Failed to send notification',
  successDeleteUserMsg: 'User deleted successfully',
  failDeleteUserMsg: 'Failed to delete user',

  // ** Users
  userChangePasswordTitle: 'Change Password',
  userResetPasswordTitle: 'Reset Password For',
  userSendNotificationToTitle: 'Send Notification To',
  userCannotDeleteTitle: 'Cannot delete',
  userHasBeenUsedTitle: 'This user has already been used',
  userDeleteUserTitle: 'Delete User',
  userTitle: 'User',
  userEmailTitle: 'Email',
  userSendNotificationTitle: 'Send Notification',
  noUserFound: 'No User Found',
  suspendUserTitle: 'Suspend User',
  suspendUserDescriptionTitle: 'User is not able to access mobile app',
  noWalletHistoryFound: 'No Wallet History Found',
  userWalletHistoryIdTitle: '#',
  userWalletHistoryAmountTitle: 'Amount',
  userWalletHistoryDateTitle: 'Date',
  noRatingsFound: 'No Ratings Found',
  userTripDetailsTitle: 'Trip Details',
  userTripRouteTitle: 'Trip Route',
  userTripImageTitle: 'Trip Image',
  userTrackingTitle: 'Tracking',
  userTripCreatedTitle: 'Created',
  userTripDriverAcceptanceTitle: 'Driver Acceptance',
  userTripStartedTitle: 'Trip Started',
  userTripStopsTitle: 'Stops',
  userTripDestinationReachedTitle: 'Destination Reached',
  userTripsInLast6MonthsTitle: 'Trips In Last 6 Months',
  userTripsTotalAmountTitle: 'Total amount $8,540',
  userTripsCountTitle: 'Trip count',
  userTripsCount: '438',
  userTripsAmountTitle: 'Trip Amount',
  userTripsAmountCount: '$22.4k',
  userTripsByPaymentMethodTitle: 'Trips By Payment Method',
  userTripsTotalAmount: 'Total amount $42,580',
  userTripStartTimeTitle: 'Start Time',
  userTripEndTimeTitle: 'End Time',
  userEditProfileDetailsTitle: 'Profile Details',
  userFirstNameTitle: 'First Name',
  userLastNameTitle: 'Last Name',
  userEmailTitle: 'Email',
  userOrganizationTitle: 'Organization',
  userPhoneNumberTitle: 'Phone Number',
  userAddressTitle: 'Address',
  userStateTitle: 'State',
  userZipCodeTitle: 'Zip Code',
  userGenderTitle: 'Gender',
  userPasswordRequirementsTitle: 'Password Requirements:',
  userPasswordRequirementsOneTitle: 'Minimum 8 characters long - the more, the better',
  userPasswordRequirementsTwoTitle: 'At least one lowercase character',
  userPasswordRequirementsThreeTitle: 'At least one number, symbol, or whitespace character',
  userEditBusinessDetailsTitle: 'Company Information',
  userEditCompanyNameTitle: 'Name',
  userEditCompanyAddressTitle: 'Address',
  userEditCompanyEmailTitle: 'Email',
  userEditCompanyUIDTitle: 'UID',

  // ** Q-N-A Question Response/Toast Messages
  failToGetQNAList: 'Fail to get QNA list',
  addQNAMsg: 'New QNA created successfully !!!',
  failToAddQNAMsg: 'Fail to add QNA data',
  failToGetQNADetailMsg: 'Fail to get QNA details',
  failToGetQNAQuestionDetailMsg: 'Fail to get QNA question details',
  updateQNAMsg: 'QNA data update successfully',
  failToUpdateQNAMsg: 'QNA is not updated',
  updateQNAStatusMsg: 'QNA status updates successfully',
  failToUpdateQNAStatusMsg: 'Fail to update QNA status',
  deleteQNAMsg: 'QNA deleted successfully',
  failToDeleteQNAMsg: 'Fail to delete QNA',

  // ** Q-N-A Question Response/Toast Messages
  failToGetQNAQuestionList: 'Fail to get QNA question list',
  addQNAQuestionMsg: 'New QNA question created successfully !!!',
  failToAddQNAQuestionMsg: 'Fail to add QNA question data',
  updateQNAQuestionMsg: 'QNA question data update successfully',
  failToUpdateQNAQuestionMsg: 'QNA question is not updated',
  updateQNAQuestionStatusMsg: 'QNA question status updates successfully',
  failToUpdateQNAQuestionStatusMsg: 'Fail to update QNA question status',
  deleteQNAQuestionMsg: 'QNA question deleted successfully',
  failToDeleteQNAQuestionMsg: 'Fail to delete QNA question',

  // ** Driver Response/Toast Messages
  failToGetDriversList: 'Fail to get driver list',
  addDriversMsg: 'Driver successfully add',
  failToAddDriversMsg: 'Fail to add driver data',
  failToGetDriversDetailMsg: 'Fail to get driver details',
  updateDriversMsg: 'Driver data update successfully',
  failToUpdateDriversMsg: 'Fail to update driver data',
  updateDriversStatusMsg: 'Driver status updates successfully',
  failToUpdateDriversStatusMsg: 'Fail to update driver status',
  deleteDriversMsg: 'Driver deleted successfully',
  failToDeleteDriversMsg: 'Fail to delete driver',
  failToGetDriverList: 'Fail to get drivers list',
  failToGetCarsList: 'Fail to get cars list',
  passwordUpdateSuccessfulMsg: 'Password updated successfully',
  failToUpdateProfilePassword: 'Failed to update password',
  successSendNotificationMsg: 'Notification send successfully',
  failSendNotificationMsg: 'Failed to send notification',
  failToGetTripList: 'Fail to get trip list',
  failToGetRatingList: 'Fail to get rating list',

  // ** Cars Response/Toast Messages
  failToGetCarsList: 'Fail to get cars list',
  addCarsMsg: 'Cars successfully add',
  failToAddCarsMsg: 'Fail to add cars data',
  failToGetCarsDetailMsg: 'Fail to get cars details',
  updateCarsMsg: 'Cars data update successfully',
  failToUpdateCarsMsg: 'Fail to update cars data',
  updateCarsStatusMsg: 'Cars status updates successfully',
  failToUpdateCarsStatusMsg: 'Fail to update cars status',
  deleteCarsMsg: 'Cars deleted successfully',
  failToDeleteCarsMsg: 'Fail to delete cars',

  // ** missing-report
  failToGetMissingReportList: 'Fail to get missing report list',

  // ** Contact Us
  contactUsSubjectPlaceHolder: 'This is join mail',
  failToGetContactUsList: 'Fail to get contact us list',
  updateContactUsStatusMsg: 'Contact us status updates successfully',
  failToUpdateContactUsStatusMsg: 'Fail to update contact us status',

  // ** settings
  failToGetSettingList: 'Fail to get settings list',
  updateSettingMsg: 'Unable to update setting',

  // ** Dashboard Response/Toast Messages
  failToGetDashboardDetails: 'Fail to get dashboard details',

  // ** Invoice Response/Toast Messages
  failToGetInvoiceList: 'Fail to get invoice list',
  failToGetInvoiceDetails: 'Fail to get invoice details',
  invoiceGenerateSuccessfullyMsg: 'Invoice generate successfully',
  failToGenerateInvoice: 'Fail to generate invoice',
  invoiceMarkAsPaidMsg: 'Invoice mark as paid successfully',
  failToMarkAsPaidMsg: 'Fail to mark as paid',

  // ** sms template Response/Toast Messages
  translateValuePlaceHolder: 'Menu Permission',
  failToGetTranslateLanguageList: 'Unable to get translate language list',
  failToGetTranslateComponentList: 'Unable to get translate component list',
  failToGetTranslateLanguageComponentList: 'Unable to get translate language component list',
  failToGetTranslateLanguageComponentList: 'Unable to get translate language component json list',
  addComponentMsg: 'Component added successfully',
  failToAddComponentMsg: 'Failed to add component',
  updateComponentMsg: 'Component updated successfully',
  failToUpdateComponentMsg: 'Unable to update component',
  deleteComponentMsg: 'Component deleted successfully',
  failToDeleteComponentMsg: 'Failed to delete component',
  updateComponentKeysMsg: 'Language data updated successfully',
  failToUpdateComponentKeysMsg: 'Language data is not updated.',

  // ** Translation
  translateTypeFieldKey: 'type',
  translateTypeFieldTitle: 'Module',
  translateTypeValueFieldTitle: 'Value',

  // Optilab Basic
  optilabBasicCompanyName: 'company_name',
  optilabBasicGstNumber: 'gst_number',
  optilabBasicAddressOneKey: 'address_line_one',
  optilabBasicAddressTwoKey: 'address_line_two',
  optilabBasicPanKey: 'pan_number',
  optilabBasicMobileNumberKey: 'mobile_number',
  optilabBasicMobileAlternateNumberKey: 'alternate_mobile_number',
  optilabBasicCountryKey: 'country',
  optilabBasicEmailKey: 'email',
  optilabBasicWebsiteKey: 'website'
}
